[build]
  publish = "."
  functions = "netlify/functions"

[functions."bluefolder-sync"]
  schedule = "0,30 * * * *"

[functions."salesforce-report-sync-trigger"]
  schedule = "*/20 * * * *"

[functions."check-report-sync-health"]
  schedule = "15,35,55 * * * *"
